### ISSUE TITLE
Deadpendency complains that asserts is unhealthy

### ISSUE THREAD

**Issue by fniessink** [srittau/python-asserts#84]
Deadpendency complains:

- asserts – [📖](https://github.com/srittau/python-asserts) [📦](https://pypi.org/project/asserts)
  - ❌ Last package release over 24 months ago. Last release: 2020-10-27

See https://github.com/ICTU/quality-time/pull/4738/checks?check_run_id=8938636809

Would it be feasible to make a new release? Maybe remove the alpha classifier? We have been using asserts in [Quality-time](https://github.com/ICTU/quality-time/tree/master/tests/feature_tests/steps) for a few years now without any problems.

**Comment by srittau** [comment]
Thank you for the report. I'll try to release a new version this week.

**Comment by srittau** [comment]
I just release python-asserts 0.12.0, which drops Python 3.6 support.

**Comment by fniessink** [comment]
Thanks so much for the quick response!
